# Kolmogorov-Smirnov test

# install and load the 'ks' package
install.packages("ks")
library(ks)

# Example data
x <- rnorm(100)
y <- rnorm(50, mean = 1, sd = 0.5)

# Perform the Kolmogorov-Smirnov test
ks.test(x, y)

# In this example, the Kolmogorov-Smirnov test is being used to compare the 
# distribution of two datasets, 'x' and 'y'. 'x' is generated by normal distribution 
# with mean=0 and sd=1 and 'y' is generated by normal distribution with mean=1, sd=0.5.


# Here, D is the maximum difference between the cumulative distribution functions 
# of the two datasets and p-value is the probability of observing a D value as extreme 
# or more extreme than the one calculated, assuming the null hypothesis 
# (that the two datasets have the same distribution) is true. 
# 
# The p-value is less than .05 so we reject the null hypothesis, which means both 
# datasets have different distribution.
# 
# You can also use the ks.test(x, y, alternative="less/greater") to specify one-sided test.